---
name: github_repository_stars
description: A new Flutter project. Created by Slidy
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter
  graphql: ^3.1.0
  gql_code_gen: ^0.1.5
  url_launcher: ^5.7.2
  equatable: ^1.2.5
dev_dependencies:
  mockito: ^4.1.2
  mobx_codegen: ^1.1.0+2
  build_runner: null
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs

